Use `pip-compile-multi` option `--autoresolve`
scipp/copier_template pull request #106
Opened 2023-11-23 13:59 UTC by nvaytet

2023-11-23 14:40 UTC, nvaytet commented
It seems that `virtualenv` now supports `platformdirs4` (see https://github.com/pypa/virtualenv/pull/2664), so it now resolves fine without pinning to `<3`.

The issue with `prompt-toolkit` remains, but gets resolved by `--autoresolve`.

2023-11-23 14:45 UTC, jl-wynen approved these changes

2023-11-23 14:45 UTC, jl-wynen commented on template/requirements/all.in
Can you add a comment about the purpose of this file? We should communicate that nobody should make an env from it.

2023-11-23 15:00 UTC, nvaytet commented on template/requirements/all.in
Maybe that `all.in` file should actually be generated from the list of files in the `requirements` folder?

2023-11-23 15:22 UTC, jl-wynen commented on template/requirements/all.in
Good point!

2023-11-23 15:23 UTC, jl-wynen requested changes

2023-11-23 15:46 UTC, jl-wynen commented on template/requirements/make_deps.py
> +    )
Minor: This would be more readable with a single multiline string.

2023-11-24 08:06 UTC, merged

2023-11-24 10:22 UTC, nvaytet commented
@jl-wynen this doesn't work with the `nightly.in` files.
It will then use e.g. `scipp @ https://github.com/scipp/scipp/releases/download/nightly/scipp-nightly-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` in all `.txt` files.

So I think we need to go back to pinning the `prompt-toolkit` version :-(